# Generated by Django 4.1.1 on 2022-09-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='athletes',
            new_name='participants',
        ),
    ]
