# Generated by Django 4.1.1 on 2022-09-24 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0002_rename_athletes_event_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='last_name',
        ),
    ]
